import { jsPDF } from 'jspdf'

function Itinerary({ itinerary, tripData, onBack }) {
  const { flights, hotels, dailyPlan, guides } = itinerary

  // Generate and download PDF
  const downloadPDF = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    let yPos = 20
    const leftMargin = 15
    const contentWidth = pageWidth - 30
    const lineHeight = 6

    // Helper function to add new page if needed
    const checkPageBreak = (requiredSpace = 25) => {
      if (yPos + requiredSpace > pageHeight - 25) {
        addFooter()
        doc.addPage()
        yPos = 20
        return true
      }
      return false
    }

    // Helper to remove ALL emojis and special characters
    const cleanText = (text) => {
      if (!text) return ''
      return text
        .replace(/[\u{1F300}-\u{1FAFF}]/gu, '')  // All emojis
        .replace(/[\u{2600}-\u{27BF}]/gu, '')    // Misc symbols
        .replace(/[\u{FE00}-\u{FE0F}]/gu, '')    // Variation selectors
        .replace(/[\u{1F000}-\u{1F02F}]/gu, '')  // Mahjong tiles
        .replace(/[^\x00-\x7F]/g, '')            // Non-ASCII
        .replace(/^\s*[-:]\s*/, '')              // Leading dashes/colons
        .trim()
    }

    // Add footer to current page
    const addFooter = () => {
      doc.setFillColor(26, 58, 92)
      doc.rect(0, pageHeight - 12, pageWidth, 12, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.text('Generated by Yuva Yatra | AI-Powered Travel Planning', pageWidth / 2, pageHeight - 5, { align: 'center' })
    }

    // ===== PAGE 1: COVER =====
    // Header background
    doc.setFillColor(26, 58, 92)
    doc.rect(0, 0, pageWidth, 60, 'F')
    
    // Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(28)
    doc.setFont('helvetica', 'bold')
    doc.text('YUVA YATRA', pageWidth / 2, 25, { align: 'center' })
    
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text('From Inputs to Itineraries', pageWidth / 2, 35, { align: 'center' })
    
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(`Your Trip to ${tripData?.destination}`, pageWidth / 2, 50, { align: 'center' })
    
    yPos = 75

    // Trip Summary Box
    doc.setFillColor(245, 166, 35)
    doc.roundedRect(leftMargin, yPos - 8, contentWidth, 30, 4, 4, 'F')
    
    doc.setTextColor(26, 58, 92)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    
    const col1 = leftMargin + 10
    const col2 = pageWidth / 2 - 15
    const col3 = pageWidth - 55
    
    doc.text('FROM', col1, yPos)
    doc.text('BUDGET', col2, yPos)
    doc.text('DURATION', col3, yPos)
    
    doc.setFontSize(12)
    doc.text(tripData?.startLocation || 'N/A', col1, yPos + 10)
    doc.text(`Rs. ${parseInt(tripData?.budget || 0).toLocaleString('en-IN')}`, col2, yPos + 10)
    doc.text(`${tripData?.days} Days`, col3, yPos + 10)
    
    yPos += 40

    // ===== FLIGHTS SECTION =====
    doc.setFillColor(26, 58, 92)
    doc.roundedRect(leftMargin, yPos, contentWidth, 10, 2, 2, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('FLIGHT OPTIONS', leftMargin + 5, yPos + 7)
    yPos += 18

    doc.setTextColor(50, 50, 50)
    doc.setFontSize(10)
    
    flights?.slice(0, 3).forEach((flight) => {
      checkPageBreak(20)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(26, 58, 92)
      doc.text(flight.platform, leftMargin + 5, yPos)
      yPos += 5
      
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(80, 80, 80)
      const desc = doc.splitTextToSize(cleanText(flight.description), contentWidth - 15)
      doc.text(desc, leftMargin + 5, yPos)
      yPos += desc.length * 5 + 4
    })

    yPos += 8

    // ===== HOTELS SECTION =====
    checkPageBreak(50)
    doc.setFillColor(26, 58, 92)
    doc.roundedRect(leftMargin, yPos, contentWidth, 10, 2, 2, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('ACCOMMODATION OPTIONS', leftMargin + 5, yPos + 7)
    yPos += 18

    doc.setTextColor(50, 50, 50)
    doc.setFontSize(10)
    
    hotels?.slice(0, 4).forEach((hotel) => {
      checkPageBreak(20)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(26, 58, 92)
      doc.text(hotel.platform, leftMargin + 5, yPos)
      yPos += 5
      
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(80, 80, 80)
      const desc = doc.splitTextToSize(cleanText(hotel.description), contentWidth - 15)
      doc.text(desc, leftMargin + 5, yPos)
      yPos += desc.length * 5 + 4
    })

    // Add footer to first page
    addFooter()

    // ===== DAY-BY-DAY ITINERARY (New Page) =====
    doc.addPage()
    yPos = 20

    // Section header
    doc.setFillColor(26, 58, 92)
    doc.rect(0, 0, pageWidth, 25, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('DAY-BY-DAY ITINERARY', pageWidth / 2, 16, { align: 'center' })
    
    yPos = 35

    dailyPlan?.forEach((day, index) => {
      checkPageBreak(60)
      
      // Day header
      doc.setFillColor(245, 166, 35)
      doc.roundedRect(leftMargin, yPos, contentWidth, 12, 3, 3, 'F')
      
      doc.setTextColor(26, 58, 92)
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      
      // Clean day title
      let dayTitle = cleanText(day.title || `Day ${index + 1}`)
      dayTitle = dayTitle.replace(/^Day\s*\d+\s*[-:]\s*/i, '')
      doc.text(`DAY ${index + 1}: ${dayTitle.toUpperCase()}`, leftMargin + 5, yPos + 8)
      yPos += 20

      // Activities
      doc.setTextColor(60, 60, 60)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      
      day.activities?.forEach((activity, actIdx) => {
        checkPageBreak(12)
        
        let cleanActivity = cleanText(activity)
        // Remove time prefixes like "Morning:", "Evening:", etc.
        cleanActivity = cleanActivity.replace(/^(Morning|Afternoon|Evening|Night|Mid-day|Early morning|Breakfast|Lunch|Dinner)\s*[:]\s*/i, '')
        
        if (cleanActivity.length > 0) {
          // Add bullet point number
          doc.setFont('helvetica', 'bold')
          doc.setTextColor(245, 166, 35)
          doc.text(`${actIdx + 1}.`, leftMargin + 5, yPos)
          
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(60, 60, 60)
          const lines = doc.splitTextToSize(cleanActivity, contentWidth - 20)
          doc.text(lines, leftMargin + 15, yPos)
          yPos += lines.length * lineHeight + 2
        }
      })
      
      yPos += 10
    })

    // ===== LOCAL GUIDES SECTION =====
    checkPageBreak(80)
    yPos += 5
    
    doc.setFillColor(26, 58, 92)
    doc.roundedRect(leftMargin, yPos, contentWidth, 10, 2, 2, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('LOCAL GUIDES & TOUR OPERATORS', leftMargin + 5, yPos + 7)
    yPos += 18

    guides?.forEach((guide) => {
      checkPageBreak(25)
      
      // Guide name
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(26, 58, 92)
      doc.setFontSize(11)
      doc.text(guide.name, leftMargin + 5, yPos)
      yPos += 6
      
      // Specialty
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(80, 80, 80)
      doc.setFontSize(9)
      doc.text(cleanText(guide.specialty), leftMargin + 5, yPos)
      yPos += 5
      
      // Contact info
      if (guide.phone) {
        doc.text(`Phone: ${guide.phone}`, leftMargin + 5, yPos)
        yPos += 5
      }
      if (guide.website) {
        doc.setTextColor(26, 58, 92)
        doc.text(`Web: ${guide.website}`, leftMargin + 5, yPos)
        yPos += 5
      }
      
      yPos += 5
    })

    // Add footer to last page
    addFooter()

    // Add page numbers
    const totalPages = doc.internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(255, 255, 255)
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - 25, pageHeight - 5)
    }

    // Save the PDF
    const fileName = `YuvaYatra_${tripData?.destination?.replace(/\s+/g, '_')}_Itinerary.pdf`
    doc.save(fileName)
  }

  return (
    <div className="page itinerary-page">
      <div className="container">
        {/* Back Button */}
        <div className="back-btn" onClick={onBack}>
          ← Back to Home
        </div>

        {/* Header */}
        <header className="itinerary-header">
          <h1>Your Trip to {tripData?.destination}</h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem' }}>
            Here's your AI-powered personalized travel plan
          </p>
          
          <div className="trip-summary">
            <div className="trip-tag">
              <span>📍</span> From {tripData?.startLocation}
            </div>
            <div className="trip-tag">
              <span>💰</span> Budget: ₹{parseInt(tripData?.budget).toLocaleString('en-IN')}
            </div>
            <div className="trip-tag">
              <span>📅</span> {tripData?.days} Days
            </div>
          </div>

          {/* Download PDF Button */}
          <button 
            className="btn btn-download" 
            onClick={downloadPDF}
            style={{ marginTop: '1.5rem' }}
          >
            📥 Download PDF Itinerary
          </button>
        </header>

        {/* Flights Section */}
        <section className="itinerary-section">
          <h2 className="section-title">
            <span>✈️</span> Flight Options
          </h2>
          <div className="booking-cards">
            {flights?.map((flight, index) => (
              <div key={index} className="booking-card">
                <div className="booking-card-header">
                  <div className="booking-logo">✈️</div>
                  <div>
                    <div className="booking-name">{flight.platform}</div>
                    <div className="booking-type">Flight Booking</div>
                  </div>
                </div>
                <p className="booking-details">{flight.description}</p>
                <a 
                  href={flight.link} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="booking-link"
                >
                  Book Now →
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* Hotels Section */}
        <section className="itinerary-section">
          <h2 className="section-title">
            <span>🏨</span> Stay Options
          </h2>
          <div className="booking-cards">
            {hotels?.map((hotel, index) => (
              <div key={index} className="booking-card">
                <div className="booking-card-header">
                  <div className="booking-logo">🏨</div>
                  <div>
                    <div className="booking-name">{hotel.platform}</div>
                    <div className="booking-type">Accommodation</div>
                  </div>
                </div>
                <p className="booking-details">{hotel.description}</p>
                <a 
                  href={hotel.link} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="booking-link"
                >
                  View Hotels →
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* Daily Itinerary */}
        <section className="itinerary-section">
          <h2 className="section-title">
            <span>🗓️</span> Day-by-Day Plan
          </h2>
          <div className="day-cards">
            {dailyPlan?.map((day, index) => (
              <div key={index} className="day-card">
                <div className="day-header">
                  <div className="day-number">{index + 1}</div>
                  <h3 className="day-title">{day.title}</h3>
                </div>
                <div className="day-activities">
                  <ul>
                    {day.activities?.map((activity, actIndex) => (
                      <li key={actIndex}>{activity}</li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Local Guides Section */}
        <section className="itinerary-section">
          <h2 className="section-title">
            <span>🧭</span> Local Guides & Tour Organizations
          </h2>
          <div className="booking-cards">
            {guides?.map((guide, index) => (
              <div key={index} className="guide-card">
                <div className="guide-avatar">🧑‍🦱</div>
                <div className="guide-info">
                  <div className="guide-name">{guide.name}</div>
                  <div className="guide-specialty">{guide.specialty}</div>
                  <div className="guide-contact">
                    {guide.phone && (
                      <span className="contact-item">
                        <span>📞</span> {guide.phone}
                      </span>
                    )}
                    {guide.email && (
                      <span className="contact-item">
                        <span>✉️</span> {guide.email}
                      </span>
                    )}
                    {guide.website && (
                      <a 
                        href={guide.website} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="contact-item"
                        style={{ color: 'var(--primary)' }}
                      >
                        <span>🌐</span> Website
                      </a>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Footer */}
        <footer style={{ textAlign: 'center', padding: '3rem 0', color: 'var(--text-muted)' }}>
          <p>Made with ❤️ by Yuva Yatra • AI-Powered Travel Planning</p>
          <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', marginTop: '1.5rem', flexWrap: 'wrap' }}>
            <button 
              className="btn btn-download" 
              onClick={downloadPDF}
            >
              📥 Download PDF
            </button>
            <button 
              className="btn btn-primary" 
              onClick={onBack}
            >
              Plan Another Trip
            </button>
          </div>
        </footer>
      </div>
    </div>
  )
}

export default Itinerary
